apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels: { app: oauth2-proxy }
  template:
    metadata:
      labels: { app: oauth2-proxy }
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          ports:
            - name: http
              containerPort: 4180
          envFrom:
            - secretRef:
                name: oauth2-proxy-secret
          args:
            - --http-address=0.0.0.0:4180
            - --provider=oidc
            - --reverse-proxy=true
            - --proxy-prefix=/oauth2
            - --whitelist-domain=.${BASE_DOMAIN}
            - --cookie-domain=.${BASE_DOMAIN}

            - --oidc-issuer-url=http://${KEYCLOAK_HOST}.${BASE_DOMAIN}/realms/${KEYCLOAK_REALM}
            - --redirect-url=http://${DEMO_HOST}.${BASE_DOMAIN}/oauth2/callback

            - --skip-oidc-discovery=true
            - --login-url=http://${KEYCLOAK_HOST}.${BASE_DOMAIN}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth

            - --redeem-url=http://keycloak.${NAMESPACE}.svc.cluster.local/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
            - --oidc-jwks-url=http://keycloak.${NAMESPACE}.svc.cluster.local/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

            - --upstream=http://demo-app.${NAMESPACE}.svc.cluster.local:80
            - --email-domain=*
            - --cookie-secure=false
            - --cookie-samesite=lax
            - --set-authorization-header=true
            - --pass-authorization-header=true
            - --pass-access-token=true

          readinessProbe:
            httpGet: { path: /ping, port: 4180 }
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: ${NAMESPACE}
  labels:
    app: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180

